version: "3.8"

services:
  xadrez-postgres:
    image: postgres:14.0-alpine
    container_name: xadrez-postgres
    restart: always
    volumes:
      - xadrez-pg-data:/var/lib/postgresql/data
    network_mode: "host"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  xadrez-spring:
    image: ghcr.io/grupinix/xadrez-spring:latest
    container_name: xadrez-spring
    restart: always
    depends_on:
      - xadrez-postgres
    network_mode: "host"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  xadrez-vue:
    image: ghcr.io/grupinix/xadrez-vue:latest
    container_name: xadrez-vue
    restart: always
    volumes:
      - /home/ubuntu/ssl:/ssl/
    depends_on:
      - xadrez-postgres
    network_mode: "host"

volumes:
  xadrez-pg-data:
