version: "3.8"

services:
  test-xadrez-postgres:
    image: postgres:14.0-alpine
    container_name: test-xadrez-postgres
    restart: unless-stopped
    volumes:
      - test-xadrez-pg-data:/var/lib/postgresql/data
    network_mode: "host"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

volumes:
  test-xadrez-pg-data:
