version: "3.8"

services:
  xadrez-postgres:
    image: postgres:14.0-alpine
    container_name: xadrez-postgres
    restart: unless-stopped
    volumes:
      - xadrez-pg-data:/var/lib/postgresql/data
    network_mode: "host"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  xadrez-spring:
    build:
      context: .
      dockerfile: ./docker/spring/Dockerfile
    image: xadrez-spring
    container_name: xadrez-spring
    depends_on:
      - xadrez-postgres
    network_mode: "host"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  xadrez-vue:
    build:
      context: .
      dockerfile: ./docker/vue/Dockerfile
    image: xadrez-vue
    container_name: xadrez-vue
    depends_on:
      - xadrez-postgres
    network_mode: "host"

volumes:
  xadrez-pg-data:
